font_family "EnvyCodeR Nerd Font Propo"
font_size 21.0
remember_window_size  yes
tab_bar_edge top
tab_bar_style slant
tab_bar_background none
background_opacity 0.9
# background_blur 1

shell fish
editor nvim

allow_remote_control no
listen_on none
update_check_interval 0
wayland_titlebar_color system

# cyberdream theme for kitty
background            #16181a
foreground            #ffffff
cursor                #ffffff
cursor_text_color     #16181a
selection_background  #3c4048
color0                #16181a
color8                #3c4048
color1                #ff6e5e
color9                #ff6e5e
color2                #5eff6c
color10               #5eff6c
color3                #f1ff5e
color11               #f1ff5e
color4                #5ea1ff
color12               #5ea1ff
color5                #bd5eff
color13               #bd5eff
color6                #5ef1ff
color14               #5ef1ff
color7                #ffffff
color15               #ffffff
selection_foreground  #ffffff
active_tab_foreground #000000
active_tab_background #ffbd5e
inactive_tab_foreground #ffffff
inactive_tab_background #16181a
